# Generated by Django 2.2.9 on 2020-09-06 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0002_copdbcity'),
    ]

    operations = [
        migrations.AddField(
            model_name='copdbcity',
            name='hq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geolocation.Address'),
        ),
        migrations.AlterField(
            model_name='copdbcity',
            name='epicenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geolocation.Coordinates'),
        ),
    ]
