# Generated by Django 2.2.9 on 2020-09-07 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0003_auto_20200905_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copdbcity',
            name='epicenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='geolocation.Coordinates'),
        ),
    ]
