# Generated by Django 3.1 on 2020-09-01 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32)),
                ('discipline', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Cop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128)),
                ('age', models.CharField(max_length=128)),
                ('badge_number', models.CharField(max_length=128)),
                ('precinct', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Force', 'Force'), ('Abuse of Authority', 'Abuse of Authority'), ('Discourtesy', 'Discourtesy'), ('Offensive Language', 'Offensive Language')], max_length=32)),
                ('detail_type', models.CharField(max_length=64)),
                ('complainant_details', models.CharField(max_length=64)),
                ('year_recieved', models.IntegerField()),
                ('conclusion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cops.conclusion')),
            ],
        ),
    ]
