# Generated by Django 3.1 on 2020-09-01 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=64)),
            ],
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='complainant_details',
            new_name='allegation',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='conclusion',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='detail_type',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='type',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='year_recieved',
        ),
        migrations.AddField(
            model_name='complaint',
            name='category',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CCRBComplainer',
            fields=[
                ('complainer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cops.complainer')),
            ],
            bases=('cops.complainer',),
        ),
        migrations.AddField(
            model_name='complaint',
            name='complainer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='cops.complainer'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CopDBComplainer',
            fields=[
                ('complainer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cops.complainer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('cops.complainer',),
        ),
        migrations.CreateModel(
            name='CCRBComplaint',
            fields=[
                ('complaint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cops.complaint')),
                ('complainant_details', models.CharField(max_length=64)),
                ('year_recieved', models.IntegerField()),
                ('conclusion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cops.conclusion')),
            ],
            bases=('cops.complaint',),
        ),
    ]
