# Generated by Django 2.2.9 on 2020-09-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cops', '0003_auto_20200903_0626'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cop',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name', 'badge_number'), name='unique_officer'),
        ),
    ]
