# Generated by Django 2.2.9 on 2020-09-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cops', '0004_auto_20200903_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='complainer',
            name='age',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='complainer',
            name='ethnicity',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='complainer',
            name='gender',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
