# Generated by Django 2.2.9 on 2020-09-03 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cops', '0006_auto_20200903_0751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copdbcomplainer',
            name='complainer_ptr',
        ),
        migrations.RemoveField(
            model_name='copdbcomplainer',
            name='user',
        ),
        migrations.RenameField(
            model_name='conclusion',
            old_name='discipline',
            new_name='finding',
        ),
        migrations.RenameField(
            model_name='conclusion',
            old_name='type',
            new_name='outcome',
        ),
        migrations.RemoveField(
            model_name='ccrbcomplaint',
            name='complainant_details',
        ),
        migrations.RemoveField(
            model_name='ccrbcomplaint',
            name='date_recieved',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='category',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='complainer',
        ),
        migrations.RemoveField(
            model_name='copdbcomplaint',
            name='copdb_complainer',
        ),
        migrations.RemoveField(
            model_name='copdbcomplaint',
            name='description',
        ),
        migrations.AddField(
            model_name='complaint',
            name='abuse_type',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='complainant_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='complainant_ethnicity',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='complainant_gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unable to determine')], default='U', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='complainant_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='contact_reason',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='cop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cops.Cop'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='date_recieved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='copdbcomplaint',
            name='complainant_account',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaint',
            name='allegation',
            field=models.CharField(max_length=128),
        ),
        migrations.DeleteModel(
            name='CCRBComplainer',
        ),
        migrations.DeleteModel(
            name='Complainer',
        ),
        migrations.DeleteModel(
            name='CopDBComplainer',
        ),
    ]
