# Generated by Django 2.2.9 on 2020-09-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cops', '0007_auto_20200903_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conclusion',
            name='finding',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='conclusion',
            name='outcome',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
