# Generated by Django 2.2.9 on 2020-09-04 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cops', '0011_auto_20200903_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='cop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cops'),
        ),
        migrations.AddField(
            model_name='copdbcomplaint',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='complaints'),
        ),
    ]
