# Generated by Django 2.2.9 on 2020-09-04 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0002_copdbcity'),
        ('cops', '0012_auto_20200904_0352'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('image', models.ImageField(blank=True, null=True, upload_to='police_departments')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='geolocation.CopDBCity')),
            ],
        ),
        migrations.AlterField(
            model_name='cop',
            name='police_department',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='copdbevent',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cops.Complaint'),
        ),
    ]
