# Generated by Django 2.2.9 on 2020-09-04 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cops', '0013_auto_20200904_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='cop',
            name='pd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cops.PoliceDepartment'),
        ),
        migrations.AlterField(
            model_name='cop',
            name='police_department',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
