# Generated by Django 2.2.9 on 2020-09-04 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cops', '0015_remove_cop_police_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cop',
            old_name='pd',
            new_name='police_department',
        ),
    ]
