# Generated by Django 2.2.9 on 2020-09-04 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cops', '0016_auto_20200904_0623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-date_recieved']},
        ),
    ]
