# Generated by Django 2.2.9 on 2020-09-06 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0003_auto_20200905_2126'),
        ('cops', '0017_auto_20200904_0629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Precinct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('image', models.ImageField(blank=True, null=True, upload_to='precints')),
                ('is_hq', models.BooleanField(default=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geolocation.Address')),
                ('coordinates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geolocation.Coordinates')),
                ('police_department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cops.PoliceDepartment')),
            ],
        ),
    ]
