# Generated by Django 2.2.9 on 2020-09-06 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cops', '0018_precinct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precinct',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geolocation.Address'),
        ),
    ]
