# Generated by Django 2.2.9 on 2020-09-06 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cops', '0020_auto_20200905_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='cop',
            name='p',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cops', to='cops.Precinct'),
        ),
    ]
