# Generated by Django 2.2.9 on 2020-09-06 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cops', '0022_remove_cop_precinct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cop',
            old_name='p',
            new_name='precinct',
        ),
    ]
