# Generated by Django 2.2.9 on 2020-09-06 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cops', '0023_auto_20200905_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='cop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='cops.Cop'),
        ),
    ]
