# Generated by Django 2.2.9 on 2020-09-06 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cops', '0024_auto_20200906_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='date_concluded',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
