# Generated by Django 2.2.9 on 2020-09-07 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cops', '0025_auto_20200906_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copdbcomplaint',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='complaints', to='geolocation.Coordinates'),
        ),
        migrations.AlterField(
            model_name='precinct',
            name='coordinates',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precincts', to='geolocation.Coordinates'),
        ),
    ]
