# Generated by Django 2.2.9 on 2020-09-08 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cops', '0026_auto_20200906_2201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='copdbevent',
            options={'ordering': ['-complaint__date_recieved']},
        ),
    ]
