# Generated by Django 2.2.9 on 2020-09-08 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cops', '0027_auto_20200907_2234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='copdbcomplaint',
            options={'ordering': ['-complaint__date_recieved']},
        ),
    ]
