# Generated by Django 2.2.9 on 2020-09-08 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cops', '0028_auto_20200907_2235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='copdbcomplaint',
            options={},
        ),
    ]
