# Generated by Django 2.2.9 on 2020-09-10 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cops', '0029_auto_20200907_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cop',
            name='police_department',
        ),
    ]
