# Generated by Django 2.2.9 on 2020-09-12 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cops', '0030_remove_cop_police_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='copdbcomplaint',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='date_recieved',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
