# Generated by Django 2.2.9 on 2020-09-14 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cops', '0031_auto_20200912_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopDBComplaintRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cop_first_name', models.CharField(blank=True, max_length=128, null=True)),
                ('cop_last_name', models.CharField(blank=True, max_length=128, null=True)),
                ('cop_sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unable to determine')], default='U', max_length=1)),
                ('cop_ethnicity', models.CharField(blank=True, max_length=16, null=True)),
                ('cop_badge_number', models.CharField(blank=True, max_length=128, null=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cops.CopDBComplaint')),
            ],
        ),
    ]
