# Generated by Django 2.2.9 on 2020-09-15 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0004_auto_20200906_2201'),
        ('cops', '0032_copdbcomplaintrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='copdbcomplaint',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='geolocation.Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='copdbevent',
            name='title',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='copdbcomplaint',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='geolocation.Coordinates'),
        ),
    ]
