# Generated by Django 3.1 on 2020-09-01 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Username')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(max_length=100, verbose_name='First name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last name')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('dob', models.DateTimeField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unable to determine')], max_length=1)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Last login')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('iOS', 'iOS'), ('Android', 'Android')], max_length=10)),
                ('device_id', models.CharField(max_length=128, unique=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('ssid', models.CharField(max_length=128)),
                ('bssid', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='AndroidDevice',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.device')),
                ('board', models.CharField(max_length=128)),
                ('bootloader', models.CharField(max_length=128)),
                ('brand', models.CharField(max_length=128)),
                ('device', models.CharField(max_length=128)),
                ('display', models.CharField(max_length=128)),
                ('fingerprint', models.CharField(max_length=128)),
                ('hardware', models.CharField(max_length=128)),
                ('host', models.CharField(max_length=128)),
                ('build_id', models.CharField(max_length=128)),
                ('manufacturer', models.CharField(max_length=128)),
                ('model', models.CharField(max_length=128)),
                ('product', models.CharField(max_length=128)),
                ('tags', models.CharField(max_length=128)),
                ('android_type', models.CharField(max_length=128)),
                ('is_physical_device', models.CharField(max_length=128)),
                ('androidId', models.CharField(max_length=128)),
                ('systemFeatures', models.CharField(max_length=128)),
            ],
            bases=('users.device',),
        ),
        migrations.CreateModel(
            name='iOSDevice',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.device')),
                ('name', models.CharField(max_length=128)),
                ('system_name', models.CharField(max_length=128)),
                ('system_version', models.CharField(max_length=128)),
                ('model', models.CharField(max_length=128)),
                ('localized_model', models.CharField(max_length=128)),
                ('identifier_for_vendor', models.CharField(max_length=128)),
                ('is_physical_device', models.CharField(max_length=128)),
            ],
            bases=('users.device',),
        ),
        migrations.CreateModel(
            name='LocationPing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_pings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='network_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.networkinfo'),
        ),
        migrations.AddField(
            model_name='device',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=128)),
                ('given_name', models.CharField(max_length=128)),
                ('middle_name', models.CharField(max_length=128)),
                ('prefix', models.CharField(max_length=10)),
                ('suffix', models.CharField(max_length=10)),
                ('family_name', models.CharField(max_length=128)),
                ('emails_raw', models.CharField(max_length=512)),
                ('phones_raw', models.CharField(max_length=512)),
                ('addresses_raw', models.CharField(max_length=512)),
                ('company', models.CharField(max_length=128)),
                ('job_title', models.CharField(max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_creator_set', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClipboardData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=128)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clipboard_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
