# Generated by Django 2.2.9 on 2020-09-04 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200903_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
