# Generated by Django 2.2.9 on 2020-09-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_account_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkinfo',
            name='bssid',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='networkinfo',
            name='ssid',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
