# Generated by Django 2.2.9 on 2020-09-07 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0004_auto_20200906_2201'),
        ('users', '0004_auto_20200904_0617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationping',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='locationping',
            name='lng',
        ),
        migrations.AddField(
            model_name='locationping',
            name='coordinates',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='location_pings', to='geolocation.Coordinates'),
            preserve_default=False,
        ),
    ]
