# Generated by Django 2.2.9 on 2020-09-08 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200906_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='androiddevice',
            name='androidId',
        ),
        migrations.RemoveField(
            model_name='androiddevice',
            name='systemFeatures',
        ),
        migrations.AddField(
            model_name='androiddevice',
            name='android_id',
            field=models.CharField(default=0, max_length=128, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='androiddevice',
            name='system_features',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='networkinfo',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='networks', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='androiddevice',
            name='android_type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='androiddevice',
            name='board',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='androiddevice',
            name='bootloader',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='androiddevice',
            name='brand',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='androiddevice',
            name='build_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='androiddevice',
            name='device',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='androiddevice',
            name='fingerprint',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='androiddevice',
            name='hardware',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='androiddevice',
            name='host',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='androiddevice',
            name='is_physical_device',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='androiddevice',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='androiddevice',
            name='model',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='androiddevice',
            name='product',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='androiddevice',
            name='tags',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
