# Generated by Django 2.2.9 on 2020-09-14 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200909_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='areFriends',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='referenced_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referenced_contacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('body', models.CharField(max_length=256)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('sent_at', models.DateField(blank=True, null=True)),
                ('data', models.CharField(blank=True, max_length=1024, null=True)),
                ('sent', models.BooleanField()),
                ('subscribers', models.ManyToManyField(related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
