# Generated by Django 2.2.9 on 2020-09-15 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200913_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='contacts_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='location_always_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='location_while_using_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='notifications_permission',
            field=models.BooleanField(default=False),
        ),
    ]
