# Generated by Django 2.2.9 on 2020-09-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200914_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='network_info',
        ),
        migrations.AlterField(
            model_name='androiddevice',
            name='display',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='iosdevice',
            name='is_physical_device',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='iosdevice',
            name='localized_model',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='iosdevice',
            name='model',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='iosdevice',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='iosdevice',
            name='system_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='iosdevice',
            name='system_version',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
