# Generated by Django 2.2.9 on 2020-09-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200920_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(default='default_pfp.png', upload_to='users/pfps/'),
        ),
    ]
