# Generated by Django 2.2.9 on 2020-09-22 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200922_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iosdevice',
            name='identifier_for_vendor',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('display_name', 'user'), name='unoque_contact'),
        ),
        migrations.AddConstraint(
            model_name='locationping',
            constraint=models.UniqueConstraint(fields=('coordinates', 'timestamp', 'user'), name='unique_coordinates_timestamp'),
        ),
    ]
