# Generated by Django 2.2.9 on 2020-09-22 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200922_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.FloatField(blank=True, null=True)),
                ('is_charging', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='locationping',
            name='altitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationping',
            name='event',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='locationping',
            name='odometer',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationping',
            name='speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationping',
            name='battery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Battery'),
        ),
    ]
