# Generated by Django 2.2.9 on 2020-09-23 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20200922_1944'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contact',
            name='unoque_contact',
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('display_name', 'user'), name='unique_contact'),
        ),
    ]
