# Generated by Django 2.2.9 on 2020-10-05 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20200923_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='androiddevice',
            name='firebase_token',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='added',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='iosdevice',
            name='firebase_token',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
