# Generated by Django 2.2.9 on 2020-10-05 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20201004_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='androiddevice',
            name='firebase_token',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='iosdevice',
            name='firebase_token',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
