# Generated by Django 2.2.9 on 2020-10-05 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20201004_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='androiddevice',
            name='android_id',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='androiddevice',
            name='is_physical_device',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='iosdevice',
            name='identifier_for_vendor',
            field=models.CharField(max_length=128),
        ),
        migrations.AddConstraint(
            model_name='androiddevice',
            constraint=models.UniqueConstraint(fields=('android_id', 'user'), name='unique_androiddevice'),
        ),
    ]
